spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dplayer
    username: dplayer
    password: dplayer
    driver-class-name : org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
