spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dplayer
    username: dplayer
    password: dplayer
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
